### ISSUE TITLE
ConcurrentModificationException in ProcessJsPostHandler

### ISSUE THREAD

**Issue by jchafik** [dandelion/dandelion#106]
The problem area is between 172 - 179. Although the cache read/write operations are protected, none of the other operations appear to be. If one thread evicts an item from the cache, another working thread may still attempt to read it.

The following are two stack traces (one on iter.next and another on iter.remove):

```
2015-10-14 13:13:07,975 ERROR (DefaultExceptionHandler.java:142) - Uncaught exception: null
java.util.ConcurrentModificationException: null
  at java.util.LinkedHashMap$LinkedHashIterator.remove(LinkedHashMap.java:724) ~[na:1.8.0_51]
  at com.github.dandelion.thymeleaf.web.handler.impl.ProcessJsPostHandler.handle(ProcessJsPostHandler.java:177) ~[dandelion-thymeleaf-1.1.0.jar:na]
  at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:68) ~[dandelion-core-1.1.0.jar:na]
  at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:73) ~[dandelion-core-1.1.0.jar:na]
  at com.github.dandelion.core.web.DandelionFilter.doFilter(DandelionFilter.java:145) ~[dandelion-core-1.1.0.jar:na]
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) ~[catalina.jar:7.0.42]
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) ~[catalina.jar:7.0.42]
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) ~[catalina.jar:7.0.42]
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) ~[catalina.jar:7.0.42]
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) ~[catalina.jar:7.0.42]
  at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) ~[catalina.jar:7.0.42]
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) ~[catalina.jar:7.0.42]
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) ~[catalina.jar:7.0.42]
  at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) ~[catalina.jar:7.0.42]
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) ~[catalina.jar:7.0.42]
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.42]
  at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:197) [tomcat-coyote.jar:7.0.42]
  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.42]
  at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1852) [tomcat-coyote.jar:7.0.42]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
  at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

2015-10-14 13:14:20,265 ERROR (DefaultExceptionHandler.java:142) - Uncaught exception: null
java.util.ConcurrentModificationException: null
  at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711) ~[na:1.8.0_51]
  at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:734) ~[na:1.8.0_51]
  at com.github.dandelion.thymeleaf.web.handler.impl.ProcessJsPostHandler.handle(ProcessJsPostHandler.java:175) ~[dandelion-thymeleaf-1.1.0.jar:na]
  at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:68) ~[dandelion-core-1.1.0.jar:na]
  at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:73) ~[dandelion-core-1.1.0.jar:na]
  at com.github.dandelion.core.web.DandelionFilter.doFilter(DandelionFilter.java:145) ~[dandelion-core-1.1.0.jar:na]
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) ~[catalina.jar:7.0.42]
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) ~[catalina.jar:7.0.42]
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) ~[catalina.jar:7.0.42]
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) ~[catalina.jar:7.0.42]
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) ~[catalina.jar:7.0.42]
  at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) ~[catalina.jar:7.0.42]
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) ~[catalina.jar:7.0.42]
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) ~[catalina.jar:7.0.42]
  at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) ~[catalina.jar:7.0.42]
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) ~[catalina.jar:7.0.42]
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.42]
  at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:197) [tomcat-coyote.jar:7.0.42]
  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.42]
  at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:1810) [tomcat-coyote.jar:7.0.42]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
  at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
```

**Comment by RG9** [comment]
@jchafik @tduchateau 
Do you know any workaround to avoid these exceptions?

Here is some workaround - handler, that is clearing cache to avoid iteration in ProcessJsPostHandler:

```
public class ClearDandelionRequestCachePostHandler extends ProcessJsPostHandler {

    @Override
    public int getRank() {
        // have to be after {@link SaveRequestPostHandler}
        // have to be before {@link ProcessJsPostHandler}
        return 2;
    }

    @Override
    public boolean handle(HandlerContext handlerContext) {

        populateRequestAttributes(handlerContext);

        // clear cache to avoid iteration in {@link ProcessJsPostHandler}
        clearRequestCache(handlerContext);

        return false;
    }

    /** copied from {@link ProcessJsPostHandler} */
    protected void populateRequestAttributes(HandlerContext handlerContext) {
        WebContext ctx = new WebContext(handlerContext.getRequest(), handlerContext.getResponse(),
                handlerContext.getRequest().getSession().getServletContext(),
                handlerContext.getRequest().getLocale());

        String requestKey = AssetUtils.extractRequestKeyFromRequest(handlerContext.getRequest());
        RequestFlashData requestData = (RequestFlashData) handlerContext.getContext()
                .getRequestFlashDataCache().get(requestKey);

        if (requestData != null) {
            log.debug("Populating request attributes.");
            ctx.setVariables(requestData.getAttributes());
        }
    }

    protected void clearRequestCache(HandlerContext handlerContext) {
        log.debug("Clearing request cache.");
        handlerContext.getContext().getRequestFlashDataCache().clear();
    }
}
```

Expected handlers order (fragment of server logs):

```
2016-09-01 17:03:07.184  INFO 2525 --- [ost-startStop-1] com.github.dandelion.core.Context        : Post-handler (1/9) SaveRequestPostHandler (rank: 1)
2016-09-01 17:03:07.184  INFO 2525 --- [ost-startStop-1] com.github.dandelion.core.Context        : Post-handler (2/9) ClearDandelionRequestCachePostHandler (rank: 2)
2016-09-01 17:03:07.184  INFO 2525 --- [ost-startStop-1] com.github.dandelion.core.Context        : Post-handler (3/9) ProcessJsPostHandler (rank: 2)
```
