### ISSUE TITLE
ProcessJsPostHandler  could not be instantiated

### ISSUE THREAD

**Issue by mrtasln** [dandelion/dandelion#132]
I'm using spring boot **2.0.2.RELEASE** version. I  want to use dandelion datatables with thymeleaf. But when i run project, i got following error. And if i change spring boot version **1.5.x**  ,i do not get any errors

```
java.util.ServiceConfigurationError: com.github.dandelion.core.web.handler.HandlerChain: Provider com.github.dandelion.thymeleaf.web.handler.impl.ProcessJsPostHandler could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[na:1.8.0_152]
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185) ~[na:1.8.0_152]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384) ~[na:1.8.0_152]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[na:1.8.0_152]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[na:1.8.0_152]
	at com.github.dandelion.core.util.ServiceLoaderUtils.getProvidersAsList(ServiceLoaderUtils.java:61) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.Context.initHandlers(Context.java:555) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.Context.init(Context.java:157) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.Context.<init>(Context.java:131) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.web.DandelionFilter.init(DandelionFilter.java:96) ~[dandelion-core-1.1.0.jar:na]
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:285) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:112) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4637) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5282) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
Caused by: java.lang.NoClassDefFoundError: org/thymeleaf/templateresolver/TemplateResolver
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_152]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_152]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_152]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_152]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_152]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_152]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_152]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_152]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_152]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[na:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_152]
	at com.github.dandelion.thymeleaf.web.handler.impl.ProcessJsPostHandler.<clinit>(ProcessJsPostHandler.java:84) ~[dandelion-thymeleaf-1.1.0.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_152]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_152]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_152]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[na:1.8.0_152]
	... 19 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.thymeleaf.templateresolver.TemplateResolver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_152]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[na:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_152]
	... 38 common frames omitted
```

**Comment by BELAGGOUN** [comment]
Hi, did you have any update about this issue, I m in a similar situation, 
any advice about this error or how to implement instantaneously filtring on a table in thymeleaf are welcomed.
thank you
