### ISSUE TITLE
BundleLoading fails with loading Google Maps on 0.11.0

### ISSUE THREAD

**Issue by Blystad** [dandelion/dandelion#43]
Hey,

On 0.11.0 WIP my current bundles fail to load because Google Maps JavaScript API doesn't have an extension:

```
{
    "bundle": "google_maps",
    "assets": [
        {
            "name":"google_maps",
            "version": "3",
            "type":"js",
            "locations": {
                "cdn":"//maps.googleapis.com/maps/api/js?key=APIKEY"
            }
        }
    ]
}
```

Which makes this check fail: [BundleUtils.java#L171-174](https://github.com/dandelion/dandelion/blob/wip/0.11.0/dandelion-core/src/main/java/com/github/dandelion/core/storage/support/BundleUtils.java#L171-L174)

since the location doesn't end in ".js". 

This worked fine in 0.10.1. 

Stack trace:
```
Caused by: com.github.dandelion.core.DandelionException: The bundle graph is not consistent for the following reasons:
- Missing extension
   [google_maps] The extension is required in all locations.

	at com.github.dandelion.core.bundle.loader.strategy.JsonBundleLoadingStrategy.mapToBundles(JsonBundleLoadingStrategy.java:119)
	at com.github.dandelion.core.bundle.loader.AbstractBundleLoader.loadBundles(AbstractBundleLoader.java:79)
	at com.github.dandelion.core.Context.initBundleStorage(Context.java:368)
	at com.github.dandelion.core.Context.init(Context.java:139)
	at com.github.dandelion.core.Context.<init>(Context.java:116)
	at com.github.dandelion.core.web.DandelionFilter.init(DandelionFilter.java:101)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:138)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:852)
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler.deferredInitialize(JettyEmbeddedWebAppContext.java:46)
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedWebAppContext.deferredInitialize(JettyEmbeddedWebAppContext.java:36)
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.handleDeferredInitialize(JettyEmbeddedServletContainer.java:123)
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.start(JettyEmbeddedServletContainer.java:106)
```

My temporary hack has been to use IntelliJs debugger and just change the `extensionNotFound` variable at runtime.

I would argue that checking the file extension isn't necessary. You could WARN, but there is no requirement that the file extension must be anything as long as HTTP Content-Type is served correctly.

**Comment by Blystad** [comment]
I found a simpler way to trick it:

```
{
    "bundle": "google_maps",
    "assets": [
        {
            "name":"google_maps",
            "version": "3",
            "type":"js",
            "locations": {
                "cdn":"//maps.googleapis.com/maps/api/js?key=API_KEY&f=.js"
            }
        }
    ]
}
```

**Comment by tduchateau** [comment]
Actually you have emphasized an issue raised during asset mapping.
As soon as you manually specify information about bundle/asset in the bundle definition, these ones shoud take precedence over anything that can be computed by Dandelion.
It is now fixed. Thanks!

PS: just a note, the `cdn` location key has been replaced by `remote` in this version. :-)
