### ISSUE TITLE
dandelionFilter failed to start when there's an empty resource folder

### ISSUE THREAD

**Issue by wmh** [dandelion/dandelion#66]
```
Exception starting filter dandelionFilter
java.lang.NullPointerException: null
	at com.github.dandelion.core.util.scanner.WebResourceScanner.doScanForResourcePaths(WebResourceScanner.java:167) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.util.scanner.WebResourceScanner.doScanForResourcePaths(WebResourceScanner.java:175) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.util.scanner.WebResourceScanner.doScanForResourcePaths(WebResourceScanner.java:175) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.util.scanner.WebResourceScanner.doScanForResourcePaths(WebResourceScanner.java:175) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.util.scanner.WebResourceScanner.scanForResourcePaths(WebResourceScanner.java:146) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.util.scanner.WebResourceScanner.findResourcePath(WebResourceScanner.java:72) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.bundle.loader.support.BowerPreLoader.getExtraBundles(BowerPreLoader.java:121) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.Context.initBundleStorage(Context.java:451) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.Context.init(Context.java:154) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.Context.<init>(Context.java:131) ~[dandelion-core-1.1.0.jar:na]
	at com.github.dandelion.core.web.DandelionFilter.init(DandelionFilter.java:96) ~[dandelion-core-1.1.0.jar:na]
```

**Comment by tduchateau** [comment]
Thanks for reporting!

**Comment by wmh** [comment]
And if the project is package as a jar file, the error happens again even if I don't have empty folder:
```
java.lang.NullPointerException: null
        at com.github.dandelion.core.util.scanner.WebResourceScanner.doScanForResourcePaths(WebResourceScanner.java:167) ~[dandelion-core-1.1.0.jar!/:na]
        at com.github.dandelion.core.util.scanner.WebResourceScanner.scanForResourcePaths(WebResourceScanner.java:146) ~[dandelion-core-1.1.0.jar!/:na]
        at com.github.dandelion.core.util.scanner.WebResourceScanner.findResourcePath(WebResourceScanner.java:72) ~[dandelion-core-1.1.0.jar!/:na]
        at com.github.dandelion.core.bundle.loader.support.BowerPreLoader.getExtraBundles(BowerPreLoader.java:121) ~[dandelion-core-1.1.0.jar!/:na]
        at com.github.dandelion.core.Context.initBundleStorage(Context.java:451) ~[dandelion-core-1.1.0.jar!/:na]
        at com.github.dandelion.core.Context.init(Context.java:154) ~[dandelion-core-1.1.0.jar!/:na]
        at com.github.dandelion.core.Context.<init>(Context.java:131) ~[dandelion-core-1.1.0.jar!/:na]
        at com.github.dandelion.core.web.DandelionFilter.init(DandelionFilter.java:96) ~[dandelion-core-1.1.0.jar!/:na]
```

**Comment by Ivan-Masli-GDP** [comment]
Is there any workaround/solution for use with version 1.1.0 ?

**Comment by rlespinasse** [comment]
You can use dandelion 1.1.1 - http://dandelion.github.io/components/core/1.1.1/changelog/

**Comment by nocquidant** [comment]
Could the 1.1.1 version be accessible in Maven central?

**Comment by rlespinasse** [comment]
It's already the case : http://search.maven.org/#artifactdetails%7Ccom.github.dandelion%7Cdandelion%7C1.1.1%7Cpom
