### ISSUE TITLE
IllegalStateException in DandelionFilter

### ISSUE THREAD

**Issue by pioto** [dandelion/dandelion#92]
I've been trying to add Dandelion to my existing project (which has a combination of Struts 1.3 and Spring MVC 4 driving different parts of the site).

However, as soon as I add the DandelionFilter, my Strings JSP pages all seem to throw an IllegalStateException:

```
2015-08-21 09:45:32,071 [http-apr-8080-exec-2] ERROR org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/ccc].[jsp] - Servlet.service() for servlet jsp threw exception
java.lang.IllegalStateException
        at org.apache.jasper.runtime.ServletResponseWrapperInclude.getOutputStream(ServletResponseWrapperInclude.java:65)
        at javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:94)
        at com.github.dandelion.core.web.DandelionFilter.doFilter(DandelionFilter.java:154)
...
```

It seems the exception is being thrown when a `<jsp:include .../>` is used on my page.

Is there possibly some part of the basic setup that I've missed, some change I need to make to my existing JSPs, or...?

All I've done so far is:

1. Add the datatables-thymeleaf, datatables-jsp, and datatables-spring3 dependencies to my pom.xml.
2. Registered the DandelionFilter and DandelionServlet.
3. Registered the DandelionDialect and DataTablesDialect.

To resolve the issue, I just comment out the DandelionFilter registration; then, my Struts JSP pages stop throwing exceptions.

**Comment by tduchateau** [comment]
Please precise the version of Dandelion you're using. Tomcat also.
Also please ensure to meet all [requirements and follow all installation steps](http://dandelion.github.io/components/core/1.1.1/docs/html/).
Thanks

**Comment by pioto** [comment]
I'm using dandelion-core 1.1.1, and dandelion-datatables 1.1.0.

Tomcat is 8.0.9. I'm using Oracle's JDK, 1.8.0_51.

I've followed all the installation steps other than adding the taglb to my JSP files, or adding the xmlns declaration to my Thymeleaf templates. (So, I have the servlet & filter registered, plus enabled Spring's DefaultServletHandler).

I haven't yet defined any assets or bundles, nor have I created a `dandelion/dandelion.properties` file. I just wanted to confirm my existing code still functioned before moving on to those next steps.

**Comment by tduchateau** [comment]
Thx. I'll investigate and keep you posted.

**Comment by pioto** [comment]
Thanks.

For what it's worth, I confirmed this issue exists with my application on Tomcat 8.0.24.

The exception being thrown indicates "something" called `response.getWriter()` before the DandelionFilter called `response.getOutputStream()`: https://docs.oracle.com/javaee/5/api/javax/servlet/ServletResponse.html#getOutputStream()

Nothing in the code for this page seems to be calling `getWriter`, so I wonder if that's implicitly done as part of the servlet, or the `<jsp:include/>`?

I also wonder if there's some interaction here with Struts... I'll keep digging and let you know if I find anything on my end.

**Comment by pioto** [comment]
Hrm, yes, it seems quite possible that the getWriter() call is happening internally in the JSP engine:

http://stackoverflow.com/a/14110665

So, without digging more into the Dandelion code... what's the reason that this filter may be trying to call `response.getOutputStream()`? It seems to be writing content that looks like the contents of what is in my first `<jsp:include>`-loaded template file.

This filter then gets called a second time, this time with the contents of my 500 Error page (which happens to be rendered with Spring MVC + Thymeleaf instead of Struts 1 + JSP), and time no exception is thrown, and my error page displays a pretty looking 500 error...

**Comment by pioto** [comment]
Last tidbit... replacing my `<jsp:include />`s with `<%@ include ...%>`s seems to mitigate the issue as well.

**Comment by dimeptr** [comment]
I have the same problem when setting up Dandelion. My project uses Apache Tiles, and the exception is on `<tiles:insertAttribute name="name" />`. unfortunately i did not find a way to mitigate the issue so far

**Comment by dimitrisli** [comment]
I can confirm this is still an issue

**Comment by MaggiWuerze** [comment]
yep, still a problem. But i guess thats no surprise looking at the date of the latest commit...

**Comment by lbuyse** [comment]
I am also still have the same issue , Running with Spring Boot v1.3.0.RELEASE, Spring v4.2.6.RELEASE , Starting Servlet Engine: Apache Tomcat/8.0.28 and apache tiles when doing tiles ``<tiles:insertAttribute name="name" />` Is this ever going to be resolved ?? and is this project abandoned because the last commit is a long time ago??
