### ISSUE TITLE
Error using Dandelion on Google App Enigne

### ISSUE THREAD

**Issue by LusciousPear** [dandelion/dandelion#94]
I'm having problems with Dandelion in prod on Google App Engine (unrelated to #89) even when it works fine on my local App Engine simulator. 

Loading any page with Dandelion taglib gives:

    HTTP ERROR: 500
    
    Problem accessing /. Reason:
    
        protocol = https host = null

Digging into logs, I see this (forgive weird formatting):
```
WARN:oejs.HttpChannel:qtp1952937534-19: / java.lang.IllegalArgumentException: protocol = https host = null at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:170) at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:927) at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301) at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) at java.net.URL.openStream(URL.java:1037) at com.github.dandelion.core.util.ResourceUtils.getContentFromUrl(ResourceUtils.java:97) at com.github.dandelion.core.asset.locator.impl.RemoteLocator.doGetContent(RemoteLocator.java:70) at com.github.dandelion.core.asset.locator.AbstractAssetLocator.getContent(AbstractAssetLocator.java:120) at com.github.dandelion.core.asset.AssetMapper.mapToAsset(AssetMapper.java:143) at com.github.dandelion.core.asset.AssetMapper.mapToAssets(AssetMapper.java:93) at com.github.dandelion.core.asset.AssetQuery.perform(AssetQuery.java:137) at com.github.dandelion.core.web.handler.impl.AssetInjectionPostHandler.handle(AssetInjectionPostHandler.java:143) at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:68) at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:73) at com.github.dandelion.core.web.DandelionFilter.doFilter(DandelionFilter.java:145) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at com.google.apphosting.runtime.jetty9.SaveSessionFilter.doFilter(SaveSessionFilter.java:37) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContext.doScope(VmRuntimeWebAppContext.java:299) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) at org.eclipse.jetty.server.Server.handle(Server.java:497) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) at java.lang.Thread.run(Thread.java:745) 2015-08-26 02:28:53.149:WARN:oejs.HttpChannel:qtp1952937534-19: Could not send response error 500: java.lang.IllegalArgumentException: protocol = https host = null 2015-08-26 02:28:53.142:WARN:oejs.DefaultServlet:qtp1952937534-19: EXCEPTION java.lang.IllegalArgumentException: protocol = https host = null at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:170) at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:927) at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301) at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) at java.net.URL.openStream(URL.java:1037) at com.github.dandelion.core.util.ResourceUtils.getContentFromUrl(ResourceUtils.java:97) at com.github.dandelion.core.asset.locator.impl.RemoteLocator.doGetContent(RemoteLocator.java:70) at com.github.dandelion.core.asset.locator.AbstractAssetLocator.getContent(AbstractAssetLocator.java:120) at com.github.dandelion.core.asset.AssetMapper.mapToAsset(AssetMapper.java:143) at com.github.dandelion.core.asset.AssetMapper.mapToAssets(AssetMapper.java:93) at com.github.dandelion.core.asset.AssetQuery.perform(AssetQuery.java:137) at com.github.dandelion.core.web.handler.impl.AssetInjectionPostHandler.handle(AssetInjectionPostHandler.java:143) at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:68) at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:73) at com.github.dandelion.core.web.DandelionFilter.doFilter(DandelionFilter.java:145) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContext.doScope(VmRuntimeWebAppContext.java:269) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191) at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72) at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:587) at javax.servlet.http.HttpServlet.service(HttpServlet.java:618) at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) at com.googlecode.objectify.cache.AsyncCacheFilter.doFilter(AsyncCacheFilter.java:58) at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at com.github.dandelion.core.web.DandelionFilter.doFilter(DandelionFilter.java:128) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at com.google.apphosting.runtime.jetty9.SaveSessionFilter.doFilter(SaveSessionFilter.java:37) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContext.doScope(VmRuntimeWebAppContext.java:299) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) at org.eclipse.jetty.server.Server.handle(Server.java:497) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) at java.lang.Thread.run(Thread.java:745) 2015-08-26 02:28:53.144:WARN:oejs.ServletHandler:qtp1952937534-19: / java.lang.IllegalArgumentException: protocol = https host = null at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:170) at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:927) at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301) at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) at java.net.URL.openStream(URL.java:1037) at com.github.dandelion.core.util.ResourceUtils.getContentFromUrl(ResourceUtils.java:97) at com.github.dandelion.core.asset.locator.impl.RemoteLocator.doGetContent(RemoteLocator.java:70) at com.github.dandelion.core.asset.locator.AbstractAssetLocator.getContent(AbstractAssetLocator.java:120) at com.github.dandelion.core.asset.AssetMapper.mapToAsset(AssetMapper.java:143) at com.github.dandelion.core.asset.AssetMapper.mapToAssets(AssetMapper.java:93) at com.github.dandelion.core.asset.AssetQuery.perform(AssetQuery.java:137) at com.github.dandelion.core.web.handler.impl.AssetInjectionPostHandler.handle(AssetInjectionPostHandler.java:143) at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:68) at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:73) at com.github.dandelion.core.web.DandelionFilter.doFilter(DandelionFilter.java:145) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at com.google.apphosting.runtime.jetty9.SaveSessionFilter.doFilter(SaveSessionFilter.java:37) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
  	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
```

I think that Dandelion may be trying to load something over http, and GAE doesn't like it if you use https in some places and http in others. Or it may have something to do with session management? I'm not sure yet. 

I'm running Dandelion 1.0 on Jetty 8+.

**Comment by tduchateau** [comment]
Issues have been raised on Jetty. I need to fix them first before this one. Thanks!

**Comment by bahrinka** [comment]
I had the same problem after deploying my app to Heroku. It was working locally because SSL is not configured locally. Changed from 1.1.1 to 1.2.0-SNAPSHOT and the problem is gone. That was a close call. Any chance 1.2.0 will be released in 2016?
